#!/bin/bash

export TEXTDOMAIN=pacstrap-f123pi
export TEXTDOMAINDIR=./locale
#export TEXTDOMAINDIR=/usr/local/share/locale

. gettext.sh

. ./pacstrap-f123pi.lib

set -e


export HOSTNAME_=f123pi
export ROOTPWD=root
export USERNAME=f123
export USERPWD=1234

directory=0

while getopts ':dho:p:r:u:' flag
#while getopts ':dh' flag
do
case $flag in
d)
directory=1
;;
h)
usage
exit 0
;;
o)
HOSTNAME_=${OPTARG}
;;
p)
USERPWD=${OPTARG}
;;
r)
ROOTPWD=${OPTARG}
;;
u)
USERNAME=${OPTARG}
;;
:)
msg=$(gettext "Option requires an argument")
die '%s: %s -- '\''%s'\' "${0##*/}" "${msg}" "$OPTARG"
;;
?)
msg=$(gettext "Invalid option")
die '%s: %s -- '\''%s'\' "${0##*/}" "${msg}" "$OPTARG"
;;
esac
done

shift $(( OPTIND - 1 ))

(( $# )) || die "No root directory specified"

newroot=$1; shift

if (( directory )) ; then
	optiond='-d'
fi

# Basic alarmpi packages
./pacstrap-f123pi -l package_lists/alarmpi/base.pkglist ${optiond} "${newroot}"

# Basic f123pi packages
./pacstrap-f123pi -l package_lists/f123pi/base.pkglist ${optiond} "${newroot}"

# Console accessibility related packages
#./pacstrap-f123pi -l package_lists/alarmpi.a11y.pkglist ${optiond} "${newroot}"

# Development tools packages
./pacstrap-f123pi -l ./package_lists/dev/tools.pkglist ${optiond} "${newroot}"

# The MATE desktop
./pacstrap-f123pi ./package_lists/f123pi/mate.pkglist ${optiond} "${newroot}"
./pacstrap-f123pi ./package_lists/f123pi/mate.extra.pkglist ${optiond} "${newroot}"

#
# Put extra calls to pacstrap-f123pi in here when more configurations are added.
#
# Such as package lists which contain desktop packages
#


./config-base-f123pi -o "${HOSTNAME_}" -r "${ROOTPWD}" -u "${USERNAME}" -p "${USERPWD}" -d "${newroot}"

#
# Put more calls to bespoke config scripts in here.
#
# Such as when desktop environments are added which need extra configuration
#


