#!/bin/bash

export TEXTDOMAIN=pacstrap-alarmpi
#export TEXTDOMAINDIR=$PWD/locale
export TEXTDOMAINDIR=/usr/local/share/locale

. gettext.sh

set -e

progname=$0

if [ `whoami` != 'root' ]; then
	echo $(eval_gettext "Must be run as root, try: sudo \${progname}") ; echo
	exit 1
fi


if [ ! -r /opt/f123pi/f123pi.db ]; then
	echo $(gettext "Failed to find the f123pi custom repository at /opt/f123pi/f123pi.db") ; echo
	exit 1
fi

packages=(parted  dialog libnewt yajl liburcu json-c tcl tk emacs-nox espeak git package-query yaourt tclx)

chroot_="${1}"

[ -z "${chroot_}" ] && { echo $(gettext "No directory given") ; echo ; exit 1 ; }
[ -d "${chroot_}" ] || { echo $(gettext "chroot directory does not exist") ; echo ; exit 1 ; }

shift

if findmnt "${chroot_}" ; then
	echo $(eval_gettext "Pacstrapping into mount-point \${chroot_}") ; echo
	pacstrap "${chroot_}" "${packages[@]}" $@
else
echo $(eval_gettext "Pacstrapping into directory \${chroot_}") ; echo
	pacstrap -d "${chroot_}" "${packages[@]}" $@
fi


echo $(eval_gettext "\$progname completed successfully") ; echo

